# Generated by Django 3.1.3 on 2020-12-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporateuser',
            name='agreement',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='individualuser',
            name='agreement',
            field=models.BooleanField(null=True),
        ),
    ]
