# Generated by Django 3.1.3 on 2020-12-02 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201202_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporateuser',
            name='company_registration_number',
            field=models.CharField(max_length=100),
        ),
    ]
