# Generated by Django 3.1.3 on 2020-12-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c_profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notice',
        ),
        migrations.RemoveField(
            model_name='p_profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='feed',
        ),
        migrations.RemoveField(
            model_name='qna',
            name='p_user',
        ),
        migrations.DeleteModel(
            name='C_profile',
        ),
        migrations.DeleteModel(
            name='P_profile',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostComment',
        ),
        migrations.DeleteModel(
            name='Qna',
        ),
    ]
